### ISSUE TITLE
Elevation for the datasets?

### ISSUE THREAD

**Issue by Dwrety** [yidahuang/City3D_dataset#1]
Do you have the elevation map and building footprint of it. I ran the City3D program on the dataset and all seem to have elongated vertical walls

**Comment by yidahuang** [comment]
The input is lidar point clouds, without DEM data. For AHN3 and Vaihingen, there is corresponding open-source footprint data. Note that if you are using gurobi solver to run City3D, make sure to install the academic license before using it.
